### ISSUE TITLE
ENH: Add csv-diff and tsv-diff to topics so that it's shown via google

### ISSUE THREAD

**Issue by corneliusroemer** [simonw/csv-diff#27]
I searched for `tsv-diff` via Google and was led to this page where your tool doesn't actually show up. Maybe add `csv-diff` and `tsv-diff` as a topic to the repo metadata so it's more findable?

https://github.com/topics/tsv-diff

**Comment by corneliusroemer** [comment]
I again struggled to find this tool through topic search - would be great if you could fix this. Thanks!

**Comment by simonw** [comment]
Just did that, thanks for the suggestion.
