### ISSUE TITLE
Option to also print all fields in changed rows

### ISSUE THREAD

**Issue by pbrende** [simonw/csv-diff#9]
When visually scanning the output, it would be nice to also have the *un-changed* fields.  Often, critical context is provided by those fields.

**Comment by simonw** [comment]
Good idea. I'll add a `--show-unchanged` option.

**Comment by simonw** [comment]
Documentation: https://github.com/simonw/csv-diff/commit/873fde4c838ea84fc26ae3820b98b79a80a5d742?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by pbrende** [comment]
Awesome.  Works great.  I think there's a typo in the documentation.  I
believe it should be:  ... to include full details of the *changed* rows...

**Comment by simonw** [comment]
Yes good spot, thanks!
